name: Node CI

on:
  push:
    paths-ignore:
      - '**/*-.test.js'
      
jobs:
  build:

    name: Build, lint & test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo ::set-output name=nvm_node_version::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.nvm_node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.nvm_node_version }}

    - name: npm install, lint, build
      run: |
        npm ci
        npm run lint --if-present
        npm run build --if-present
          
    - name: applitools
      run: |
        export APPLITOOLS_BATCH_ID=`echo $SHA8`
        npm run eyes-storybook -u https://speed-e.github.io/componentlibrary/?path=/story/*

      env:
        SHA8: ${GITHUB_SHA::8}
        APPLITOOLS_API_KEY: CwEkK7uiI4107FPoMCtEDtoyGrbf7109rSU6U3xReLhx53w110
        NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        CI: true
