name: Node CI

on:
  push:
    paths-ignore:
      - '**/*-.test.js'
      
jobs:
  build:

    name: Build, lint & test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo ::set-output name=nvm_node_version::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.nvm_node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.nvm_node_version }}

    - name: npm install, lint, build
      run: |
        npm ci
        npm run lint --if-present
        npm run build --if-present

    - name: build Storybook
      run: npm run build-storybook

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Storybook to Azure
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch -s storybook-static -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode key --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}
      
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PAT }}
        CI: true